name: Monorepo CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    name: Build, Lint & Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: scheduler_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      rabbitmq:
        image: rabbitmq:3-management-alpine
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
        ports:
          - 5672:5672
          - 15672:15672
        options: >-
          --health-cmd "rabbitmq-diagnostics -q ping"
          --health-interval 10s
          --health-timeout 10s
          --health-retries 10
          --health-start-period 30s

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci --legacy-peer-deps || npm i --legacy-peer-deps

      - name: Check Formatting
        run: npm run format:check

      - name: Lint Workspace
        run: npm run lint

      - name: Typecheck Workspace
        run: npx tsc --noEmit

      - name: Build Workspace
        run: npm run build

      - name: Run Tests
        env:
          NODE_ENV: test
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: scheduler_db
          REDIS_HOST: localhost
          REDIS_PORT: 6379
          RABBITMQ_HOST: localhost
          RABBITMQ_PORT: 5672
          RABBITMQ_USER: guest
          RABBITMQ_PASSWORD: guest
          RABBITMQ_URL: amqp://guest:guest@localhost:5672
          JWT_SECRET: super_secret_jwt_test_key_minimum_32_characters
          SCANNER_PORT: 3003
          DISPATCHER_PORT: 3004
          WORKER_PORT: 3005
          SCHEDULER_PORT: 3002
          IDENTITY_PORT: 3001
          GATEWAY_PORT: 8080
        run: npm run test
